<?php
/**
 * Created by PhpStorm.
 * User: SAMSUNG
 * Date: 2017/11/11
 * Time: 21:58
 */

namespace backend\components;


use yii\base\ActionFilter;
use yii\web\HttpException;
use yii\web\NotAcceptableHttpException;
use yii\web\NotFoundHttpException;

class PermissionFilter extends ActionFilter
{
public function afterAction($action, $result)
{
//    if(\Yii::$app->user->isGuest){
//        header("location:/login/index");
//        exit;
//        throw new NotFoundHttpException('没有权限访问');
//    }
//    if (!\Yii::$app->user->can($action->uniqueId)){
//        throw  new HttpException("没有权限访问");
//        return 11;
//    }
    return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
}
}